version: '3'
services:
  db:
    image: postgres:13
    env_file: .env
    ports:
      - "5432:5432"

  grpc-server:
    build: .
    ports:
      - "50051:50051"
    depends_on:
      - db
    env_file: .env
